/* The browser adapter is an interface preview only. It never creates solids.
 * Its default examples are generated by the add-in's Python validation core.
 * Changed expressions must be evaluated and validated in Autodesk Fusion.
 */
(function () {
  'use strict';
  if (window.adsk && typeof window.adsk.fusionSendData === 'function') return;
  let data, current, loading, presets = [];
  const clone = (value) => JSON.parse(JSON.stringify(value));
  const emit = (action, payload) => setTimeout(() => { if (window.fusionJavaScriptHandler) window.fusionJavaScriptHandler.handle(action, JSON.stringify(payload)); }, 30);
  try { presets = JSON.parse(localStorage.getItem('gear-studio-demo-presets') || '[]'); if (!Array.isArray(presets)) presets = []; } catch (_) { presets = []; }
  function storePresets() { try { localStorage.setItem('gear-studio-demo-presets', JSON.stringify(presets)); } catch (_) { /* A private browser can still preview the interface. */ } }
  async function load() {
    if (!loading) loading = fetch('demo-data.json').then((response) => { if (!response.ok) throw new Error('The interface preview data is missing. Open Gear Studio inside Fusion, or serve the complete ui folder locally.'); return response.json(); }).then((result) => { data = result; current = clone(data.samples.spur.spec); });
    await loading;
  }
  function state(spec) { current = clone(spec); emit('state', { catalog: data.catalog, supportedKinds: data.supportedKinds, spec: current, presets, selection: null, mode: 'create', host: 'preview' }); }
  function validate(spec, requestId) {
    const sample = data.samples[spec.kind];
    const same = sample && Object.keys(sample.spec.parameters).every((key) => String(sample.spec.parameters[key]).trim() === String(spec.parameters[key]).trim());
    if (same) { const result = clone(sample.validation); result.requestId = requestId; emit('validation', result); }
    else emit('validation', { requestId, valid: false, issues: [{ field: '', code: 'preview_host', severity: 'warning', message: 'Changed expressions are validated inside Fusion. Restore last used to explore the checked example for this gear type.' }], metrics: {}, cost: {}, preview: null });
  }
  window.adsk = { fusionSendData: async function (action, jsonString) {
    const payload = JSON.parse(jsonString || '{}');
    try {
      await load();
      if (action === 'ready') state(current);
      else if (action === 'validate') validate(payload.spec, payload.requestId);
      else if (action === 'loadLast') { const sample = data.samples[payload.kind]; if (sample) state(sample.spec); else emit('error', { message: 'This family has no checked example in the interface preview.' }); }
      else if (action === 'savePreset') { const item = { id: 'preview-' + Date.now(), name: payload.name, spec: clone(payload.spec), updated_at: new Date().toISOString() }; delete item.spec.id; presets.push(item); storePresets(); emit('result', { ok: true, message: 'Preset saved for this interface preview.', presets }); }
      else if (action === 'loadPreset') { const item = presets.find((preset) => preset.id === payload.id); if (item) state(item.spec); }
      else if (action === 'deletePreset') { presets = presets.filter((preset) => preset.id !== payload.id); storePresets(); emit('result', { ok: true, message: 'Preset deleted.', presets }); }
      else if (action === 'refreshSelection') emit('selection', null);
      else emit('error', { message: 'This action needs Autodesk Fusion. The browser is an interface preview and does not create or update B-rep geometry.' });
    } catch (error) { emit('error', { message: error.message || String(error) }); }
    return 'OK';
  } };
}());
